### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by cc1024** [lzuntalented/lz-lottery-tool#1]
我有一个7+2的双色球复式守号，目前网站上只能输入单组，不方便查询。
所以请求
1. 支持复式选号模式
2. 或可存储自己的号码，不需每次都重新输入
3. 另外建议：如果结果为中奖，用红色字体显示，并显示中奖金额。

谢谢！

**Comment by lzuntalented** [comment]
网站已添加复式查询
